
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'contentHTML LATEXempty :content : content LATEX\n               | LATEX\n               | HTML\n               | empty\n    '
    
_lr_action_items = {'LATEX':([0,1,2,3,4,5,],[2,5,-3,-4,-5,-2,]),'HTML':([0,],[3,]),'$end':([0,1,2,3,4,5,],[-1,0,-3,-4,-5,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'content':([0,],[1,]),'empty':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> content","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',56),
  ('content -> content LATEX','content',2,'p_content','parser.py',61),
  ('content -> LATEX','content',1,'p_content','parser.py',62),
  ('content -> HTML','content',1,'p_content','parser.py',63),
  ('content -> empty','content',1,'p_content','parser.py',64),
]
